accounts/urls.py
from django.urls import path 
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('edit/', views.edit, name='edit'),
    path('follow_and_unfollow/', views.follow_and_unfollow, name='follow_and_unfollow'),
    path('follow/', views.follow_profile, name='follow'),
    path('unfollow/', views.unfollow_profile, name='unfollow'),
    path('delete_post/', views.delete_post, name='delete_post'),
    path('<str:username>/', views.profile, name='profile')
]

gram_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path 
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('post/', views.post, name='post'),
    path('comment/', views.comment, name='comment'),
    #path('like/', views.like, name='like'),
    #path('unlike/', views.unlike, name='unlike'), 
    path('like_unlike/', views.like_and_unlike_post, name='likeandunlike'),
    path('<str:post_caption>/', views.comments, name='comments'),
]

home/models.py
from django.db import models 
from django.contrib.auth.models import User 

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='like', blank=True)
    caption = models.TextField()
    photo = models.ImageField(upload_to='posts')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption
    
    def number_of_likes(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text

home/forms.py
from django import forms 
from .models import Post 

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('photo', 'caption',)

home/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from django.contrib.auth.models import User  
from django.contrib.auth.decorators import login_required
import json
from django.http import JsonResponse
from .models import Post, Comment
from .forms import PostForm
# Create your views here.

@login_required(login_url="accounts:signin") #restricted to only logged in users 
def home(request):
    """ get and display all posts and comments made by users """
    posts = Post.objects.all() 
    comments = Comment.objects.all() 
    context = {'posts':posts, 'comments':comments}
    return render(request, 'home/home.html', context)

def post(request):
    author = get_object_or_404(User, id=request.user.id)
    if request.method != "POST":
        form = PostForm()
    else:
        photo = request.FILES['photo'] #get posted image
        caption = request.POST['caption'] #get the caption
        form = PostForm(request.POST, request.FILES) 
        if form.is_valid():
            Post.objects.create(author=author, caption=caption, photo=photo) #create new post with POST data
            return HttpResponseRedirect(reverse('accounts:profile', args=(author,)))
    context = {'form':form}
    return render(request, 'home/post.html', context)

def like_and_unlike_post(request):
    data = json.loads(request.body) #get JSON data sent from javascript 
    person = request.user.id #get current user ID
    postid = data['postID'] #get JSON data (postID) sent from javascript and save in a variable called postid 
    post = get_object_or_404(Post, id=postid) #get post object 
    user = get_object_or_404(User, id=person) #get user object
    if user in post.likes.all(): #if user object is in list of likes relationship remove user 
        unlike = post.likes.remove(user) 
    else:
        like = post.likes.add(user) #else add user to list of likes 
    data['likesNumber'] = post.number_of_likes() #get number of post likes in database and store in Json to send back to javascript
    return JsonResponse(data)

def comment(request):
    """ javascript handles request to comment on a post without page reload (illusion) """
    data = json.loads(request.body) #get JSON data sent from javascript
    postID = data['postID'] #get JSON data (post ID) sent from javascript
    userID = request.user.id 
    comment = data['comment'] #get JSON data (comment text) sent from javascript
    post = get_object_or_404(Post, id=postID)
    user = get_object_or_404(User, id=userID)
    Comment.objects.create(post=post, author=user, text=comment) #create comment in database
    return JsonResponse(data)

def comments(request, post_caption):
    post = get_object_or_404(Post, caption=post_caption)
    comments = post.comment_set.all()
    context = {'comments':comments}
    return render(request, 'home/comments.html', context)

home/templates/home/base.html
<!-- base.html doc which contains the overall general and similar markup and styling -->
{% load bootstrap4 %}
{% bootstrap_css %} <!-- django-bootstrap4  -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> <!-- font awesom for all fa fa classes -->
    <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap" rel="stylesheet"> <!-- google fonts used for GRAM logo -->
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}"> <!-- connected to accounts app css -->
    <link rel="stylesheet" href="{% static 'home/styles.css' %}"> <!-- connected to home app css -->
    <title>{% block title %} base title {% endblock title %}</title>
</head>
<body class="bg-light">
    <nav>
    {% block nav %}
        {% if request.user.is_authenticated %}
          <nav class="container navbar fixed-top mx-auto navbar navbar-expand navbar-light bg-white">
            <a class="navbar-brand logo" href="{% url 'home:home' %}">GRAM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <form class="form-inline mx-auto searchform">
                <input class="form-control form-control-sm" type="search" placeholder="Search" aria-label="Search">
              </form>
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="#"><i class="fa fa-home"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <div class="btn-group">
                    <a class="authuser nav-link dropdown rounded-circle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <img src="{{ request.user.profile.profile_photo.url }}" width="30" height="30" class="d-inline-block align-top rounded-circle profilephoto">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <a class="dropdown-item" href="{% url 'accounts:profile' request.user.username %}"><i class="fa fa-user-circle-o"></i> Profile</a>
                      <a class="dropdown-item" href="{% url 'accounts:edit' %}"><i class="fa fa-cog"></i> Settings</a>
                      <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:signout' %}">Log Out</a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
          {% endif %}
    {% endblock nav %}
    </nav>

    <article>
        {% block article %}
        {% endblock article %}
    </article>

    <section>
      {% block section %}
      {% endblock section %}
    </section>

{% bootstrap_javascript jquery='full' %}
  <script src="{% static 'accounts/script.js' %}"></script>
  <script src="{% static 'home/scripts.js' %}"></script>
  <script type="text/javascript">
    function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
  const csrftoken = getCookie('csrftoken');
</script>
</body>
</html>

home/templates/home/comments.html
{% extends 'home/base.html' %}

{% block title %} comments {% endblock title %}

{% block article %}
    {% for comment in comments %}
    <div class="list-group mt-5">
        <button type="button" class="list-group-item bg-light text-left">
            <img class="rounded-circle" src="{{comment.author.profile.profile_photo.url}}" style="max-height: 45px; max-width: 35px;">
            <a href="{% url 'accounts:profile' comment.author %}" class="text-dark text-decoration-none">{{comment.author}}</a> 
            <span class="text-muted">{{comment.text}}</span>
        </button>
    </div>
    {% endfor %}
{% endblock article %}

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block title %} Gram {% endblock title %}

{% block article %}

{% for post in posts %}
<div class="mx-auto mt-5 card bg-white" style="max-width: 540px">
    <div class="card-header bg-white">
        <img src="{{post.author.profile.profile_photo.url}}" class="card-img-top rounded-circle" style="max-height: 45px; max-width: 35px;">
        <a href="{% url 'accounts:profile' post.author %}" class="text-dark text-decoration-none">{{post.author}}</a>
    </div>
    <img src="{{post.photo.url}}" class="card-img-top">

    <div class="card-body cardlikecom">

      {% if request.user not in post.likes.all %}
        <i class="likepost fa fa-heart-o mb-2" data-post="{{post.id}}" style="color: black;"></i> 
      {% else %}
        <i class="unlike fa fa-heart mb-2" data-post="{{post.id}}" style="color: red; font-size: 23px;"></i>
      {% endif %}

      <a class="text-dark" href="{% url 'home:comments' post.caption %}"><i class="fa fa-comment-o mb-2 ml-3"></i></a>

      <span class="pull-right bookmarkicon"><i class="fa fa-bookmark"></i></span>
      <p class="card-text likesCount" data-post="{{post.id}}">
        {{post.number_of_likes}} 
          {% if post.likes.count == 1 %}
            like 
          {% else %} 
            likes 
          {% endif %} 
      </p>
      <p class="card-text"><a href="{% url 'accounts:profile' post.author %}" class="text-dark">{{post.author}}</a> <span class="text-muted">{{post.caption}}</span></p>
       <!-- comments -->
      <hr class="border bg-dark" style="height: 2px;"> 
      <div class="input-group">
        <input type="text" class="form-control rounded comment" placeholder="Add a comment..." data-post="{{post.id}}" aria-label="Dollar amount (with dot and two decimal places)">
        <div class="input-group-append">
          <span><button class="btn btn-outline-primary addcomment" data-post="{{post.id}}">Post</button></span>
        </div>
      </div>
    </div>
</div>
{% endfor %}

{% endblock article %}

home/templates/home/post.html
{% extends 'home/base.html' %}
{% load bootstrap4 %}
{% block title %}{% endblock title %}

{% block article %}
<div class="d-flex justify-content-center mt-5">
    <form method="post" class="form w-75" enctype="multipart/form-data"> 
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary mb-4 w-100">Post</button>
      </div>
    </form>
  </div>
{% endblock article %}