accounts/urls.py
from django.urls import path 
from . import views 

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('edit/', views.edit, name='edit'),
    path('follow_and_unfollow/', views.follow_and_unfollow, name='follow_and_unfollow'),
    path('follow/', views.follow_profile, name='follow'),
    path('unfollow/', views.unfollow_profile, name='unfollow'),
    path('delete_post/', views.delete_post, name='delete_post'),
    path('<str:username>/', views.profile, name='profile')
]

gram_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path 
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('post/', views.post, name='post'),
    path('comment/', views.comment, name='comment'),
    #path('like/', views.like, name='like'),
    #path('unlike/', views.unlike, name='unlike'), 
    path('like_unlike/', views.like_and_unlike_post, name='likeandunlike'),
    path('<str:post_caption>/', views.comments, name='comments'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_photo = models.ImageField(upload_to='profile', default='profile/Anon.png')
    followers = models.ManyToManyField(User, related_name='followers')
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) 

    def number_of_followers(self):
        return self.followers.count()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

home/models.py
from django.db import models 
from django.contrib.auth.models import User 

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='like', blank=True)
    caption = models.TextField()
    photo = models.ImageField(upload_to='posts')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption
    
    def number_of_likes(self):
        return self.likes.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.models import User 


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, help_text='Required')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name' ,'password1', 'password2')

class SignInForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User 
        fields = ('username',)

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ('profile_photo', 'bio')

accounts/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse, get_object_or_404
import json
from django.http import JsonResponse
from django.contrib.auth.models import User 
from django.contrib.auth import login, authenticate, logout
from .forms import SignUpForm, SignInForm, EditProfileForm, UserEditForm
from home.models import Post
from .models import Profile

# Create your views here.

def signup(request):
    if request.method != 'POST': #display empty form if request is GET
        form = SignUpForm()
    else:
        """ get the form filled in form to authenticated and login after signup """
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(request, username=username, password=password1) 
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('home:home'))
            return HttpResponse('error, signup failed!')
    context = {'form':form}
    return render(request, 'registration/signup.html', context)

def signin(request):
    if request.method != 'POST':
        form = SignInForm()
    else:
        username = request.POST['username']
        password = request.POST['password']
        form = SignInForm(data=request.POST)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('home:home'))
        return HttpResponse('error, signin failed!')
    context = {'form':form}
    return render(request, 'registration/login.html', context)

def profile(request, username):
    user = get_object_or_404(User, username=username)
    following = Profile.objects.filter(followers=user).count() #search for username in all profiles and count the number of occurence
    posts = user.post_set.all()
    context = {'user':user, 'following':following, 'posts':posts}
    return render(request, 'accounts/profile.html', context)

def edit(request):
    if request.method != 'POST':
        """ if GET request, show form with filled in data form the current user """
        user_form = UserEditForm(instance=request.user) 
        profile_form = EditProfileForm(instance=request.user.profile)
    else: 
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:profile', args=(request.user.username,)))
        return HttpResponse('error, update failed!')
    context = {'user_form':user_form, 'profile_form':profile_form}
    return render(request, 'accounts/editprofile.html', context)

def follow_and_unfollow(request):
    data = json.loads(request.body)
    person = request.user.id
    profileID = data['profileID']
    user = get_object_or_404(User, id=person)
    profile = get_object_or_404(Profile, id=profileID)
    if user in profile.followers.all():
        unfollow = profile.followers.remove(user)
    else:
        follow = profile.followers.add(user)
    data['likeCount'] = profile.number_of_followers()
    return JsonResponse(data)

def follow_profile(request): 
    """ javascript handles request to follow profile without page roload """
    data = json.loads(request.body) #load JSON data sent from javascript and store in data
    person = request.user.id
    profileID = data['profile'] #get requested profile ID from JSON data 
    user = get_object_or_404(User, id=person) #get current user 
    profile = get_object_or_404(Profile, id=profileID) #get requested profile user ID 
    follow = profile.followers.add(user) #add current user to list of requested profileID 
    data['likeCount'] = profile.number_of_followers() #get the number of requested profileID followers as JSON to output in template through javascript
    return JsonResponse(data)

def unfollow_profile(request):
    """ javascript handles request to unfollow profile without page roload """
    data = json.loads(request.body) #load JSON data sent from javascript and store in data
    person = request.user.id
    profileID = data['profile'] #get requested profile ID from JSON data 
    user = get_object_or_404(User, id=person) #get current user 
    profile = get_object_or_404(Profile, id=profileID) #get requested profile user ID 
    follow = profile.followers.remove(user) #remove current user to list of requested profileID 
    data['likeCount'] = profile.number_of_followers() #get the number of requested profileID followers as JSON to output in template through javascript
    return JsonResponse(data)

def delete_post(request):
    data = json.loads(request.body)
    postid = data['postID']
    user = get_object_or_404(User, id=request.user.id)
    post = get_object_or_404(Post, id=postid)
    post.delete()
    return JsonResponse(data)

def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('accounts:signin'))

accounts/templates/accounts/editprofile.html
{% extends 'home/base.html' %}
{% load bootstrap4 %}

{% block title %}Edit Profile . Gram {% endblock title %}

{% block article %}
<!-- edit profile form centered with a width of 50 percent -->
<div class="d-flex justify-content-center mt-5">
  <form method="post" class="form w-75" enctype="multipart/form-data"> 
    {% csrf_token %}
    {% bootstrap_form user_form %}
    {% bootstrap_form profile_form %}
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary mb-4 w-100">Submit</button>
    </div>
  </form>
</div>
{% endblock article %}

accounts/templates/accounts/profile.html
{% extends 'home/base.html' %}

{% block title %} {{user.username}} {% endblock title %}

{% block article %}
<div class="profilecard card mb-3 mx-auto mt-5 bg-light border-0" style="max-width: 500px;">
    <div class="row no-gutters">
      <div class="col-sm-4">
        <img src="{{user.profile.profile_photo.url}}" class="card-img rounded-circle w-75">
      </div>
      <div class="col-sm-8">
        <div class="card-body">
          <h5 class="card-title">{{user.username}} 

            <!-- deals with following and follow of a profile -->
              {% if request.user in user.profile.followers.all %} <!-- show following button if user is following profile, handled with ajax to prevent page reload  -->
                <span><button class="following btn btn-sm btn-light border" data-profile="{{user.id}}">Following</button></span> 
              {% else %}
                {% if request.user.id != user.id %} <!-- if current user is not current profile, show follow button -->
                  <span><button class="follow btn btn-sm btn-primary" data-profile="{{user.id}}">Follow</button></span>
                {% else %} <!-- else is current user is current profile, show edit profile button -->
                  <a class="btn btn-light border" href="{% url 'accounts:edit' %}">Edit Profile</a> 
                  <i class="fa fa-cog"></i></span> 
                  <br><a class="text-dark" href="{% url 'home:post' %}"><i class="fa fa-plus-square-o"></i></a>
                {% endif %}
              {% endif %}
            </h5>
            <!-- end -->

          <p class="card-text">
            <span>{{user.post_set.count}} 
              {% if user.post_set.count == 1  %} post 
                {% else %} posts
              {% endif %}
            </span> 
            <span class="followers_number" data-profile="{{user.id}}">
            {{user.profile.followers.count}} 
              {% if user.profile.followers.count == 1 %} follower 
                {% else %} followers 
              {% endif %}
              </span>
              <span>{{following}} following</span>
          </p>
          <p class="card-text text-muted">{{user.profile.bio}}</p>
        </div>
      </div>
    </div>

{% endblock article %}

{% block section %}
<ul class="container nav nav-tabs font-weight-bold mt-5">
  <li class="nav-item mx-auto">
    <a class="nav-link active" href="#"><i class="fa fa-table"></i> POSTS</a>
  </li>
</ul>

<div class="container mx-auto">
  <div class="card-deck">
    {% for post in posts %}
        <div class="deleteimage card mt-5 bg-light" data-postID="{{post.id}}">
           <img class="card-img-top" src="{{ post.photo.url }}" height="290px" width="290px">
           {% if request.user.id == user.id %}
            <btn class="deletepost text-center text-danger" data-postID="{{post.id}}">delete</btn>
          {% endif %}
        </div>
        {% if forloop.counter|divisibleby:3 %}
  </div>
  <div class="card-deck">
      {% endif %}
  {% endfor %}
  </div>
</div>
{% endblock section %}